### ISSUE TITLE
Responsive compatible Mobile

### ISSUE THREAD

**Issue by Freddy03h** [parisjs/parisjs-website#106]
Hello !

Je viens de remarquer que le site n'est pas compatible mobile, enfin, pas responsive. C'est un peu dommage.

![capture d ecran 2016-02-17 a 14 17 58](https://cloud.githubusercontent.com/assets/1412159/13110630/7faefffc-d581-11e5-8dbc-31080126080e.png)

Surtout qu'en essayant deux trois coups de flexbox je pense que je peux faire ça sans trop me prendre la tête avec trop de media queries et en gardant le design original.

J'ai pas trouvé de script GAnalytics sur le site. On a pas de stats sur les browsers du coup ?

**Comment by risseraka** [comment]
Je le vois bien (et il est bloqué par ghostery, yeah!) :

```html
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-23072906-1']);
          _gaq.push(['_setDomainName', '.parisjs.org']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
```

**Comment by Freddy03h** [comment]
Par contre je viens de me rendre compte que le principal soucis va venir des images.

Vous pensez qu'on peut avoir les fichiers sources ?

![background_header](http://parisjs.org/images/bg_header.png)

Par exemple cette image pose problème, il faudrait que j'ai l'image de l'effet _grille_ sur fond transparent et la photo séparément.

Et aussi remplacer les icônes `png` par des `svg` ça serait cool aussi pour pas s'embêter avec tous les pixel-ratio !

**Comment by DjebbZ** [comment]
Ya longtemps qu'on se dit que ce serait bien d'avoir un site responsive :D
Je sais pas qui a les accès au Google Analytics. Je sais pas non plus qui a
l'image source. L'idée du svg ça faciliterait le responsive. Faudrait que
quelqu'un avec les compétences Illustrator/InkScape/Sketch/whatever s'y
colle.

@Paris.js, qui a ces infos (image et accès Analytics) ?


Khalid aka DjebbZ
@Dj3bbZ

2016-02-17 14:32 GMT+01:00 Freddy Harris <notifications@github.com>:

**Comment by Freddy03h** [comment]
Sinon on peut prendre quelques libertés avec le design originel. On pourrait prendre une bibliothèque d'icônes `svg` (en plus ça permettrait de _rafraichir_ le logo twitter :D )

**Comment by risseraka** [comment]
Freddy, t'es libre de faire ce que tu veux, après les gens donnent leur avis et on embarque ou pas.
On te crachera jamais dessus si tu essayes de faire bouger le truc. : )

**Comment by DjebbZ** [comment]
D'accord avec Adrien, fais donc ! Après, ce serait top qu'il y ait une
issue pour chaque modif, histoire que tout le monde puisse
suivre/reviewer/etc.


Khalid aka DjebbZ
@Dj3bbZ

2016-02-17 14:55 GMT+01:00 Adrien Risser <notifications@github.com>:

**Comment by Freddy03h** [comment]
Sans que je vous dise ce que je pense qui ne va pas, vous en pensez quoi ?

http://freddy03h.github.io/parisjs-website/

(pas besoin de lancer une QA intensive sur différents navigateurs/devices, j'ai pas lancer autoprefixer)

**Comment by DjebbZ** [comment]
J'aime bien l'ordre des blocks. Ça pourrait le faire. Après faudra corriger, c'est pas mettable en prod ;)

**Comment by molokoloco** [comment]
+1

Le 17 février 2016 à 18:58, Khalid Jebbari <notifications@github.com> a
écrit :

> J'aime bien l'ordre des blocks. Ça pourrait le faire. Après faudra
> corriger, c'est pas mettable en prod ;)
>
> > Le 17 févr. 2016 à 18:51, Freddy Harris <notifications@github.com> a
> écrit :
> >
> > Sans que je vous dise ce que je pense qui ne va pas, vous en pensez quoi
> ?
> >
> > http://freddy03h.github.io/parisjs-website/
> >
> > (pas besoin de lancer une QA intensive sur différents
> navigateurs/devices, j'ai pas lancer autoprefixer)
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parisjs/parisjs-website/issues/106#issuecomment-185326067>
> .
>



-- 
*Julien Guézennec *+336 61 75 64 98
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco <https://twitter.com/molokoloco/> -
http://b2bweb.fr

**Comment by revolunet** [comment]
Nice!
Le 17 févr. 2016 5:51 PM, "Freddy Harris" <notifications@github.com> a
écrit :
