### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by PierrickP** [parisjs/parisjs-website#122]
I started to redact the FAQ page, feel free to comment or ask me to add you for contributing
-> https://docs.google.com/document/d/14p8Mhvi1rxczJ0B7afh8esXxHTurdfsYwz2ezo_qyQQ/edit?usp=sharing

**Comment by PierrickP** [comment]
French version: *ok* b00ae427ed24f11fd6280eec50898ddf5649caf4
English version: *needed*

**Comment by PierrickP** [comment]
Assigned to @bobylito for the English version 😉

**Comment by molokoloco** [comment]
Oui, faut pas compter dur moi pour l'anglais ! 🤣

Le 22 nov. 2017 7:24 PM, "Pierrick PAUL" <notifications@github.com> a
écrit :

**Comment by PierrickP** [comment]
English translation added on `refonte2018`
