### ISSUE TITLE
Scroll on anchors doesn't work

### ISSUE THREAD

**Issue by fazouane-marouane** [parisjs/parisjs-website#128]
Hi,

I submitted a PR https://github.com/phenomic/phenomic/pull/1195 to fix scroll behaviour on anchors.

**Comment by PierrickP** [comment]
Any news on this? If they don't accept he PR can you make us a fix?

**Comment by fazouane-marouane** [comment]
I submitted a second version of the PR that uses reac-router-hash-link.
I'll await the reviews now.

**Comment by PierrickP** [comment]
meantime i push a patch here a044ffb5250bc6f897df7fe4a8fdb54527315ed7
