### ISSUE TITLE
Style NextMeetup

### ISSUE THREAD

**Issue by PierrickP** [parisjs/parisjs-website#133]
Add style for the `NextMeetup` component

Inspired of Meetup's next event block.
Contain:
+ title
+ date
+ link
+ count rvps (yes)
+ host name
+ address

For testing replace meetup url for `https://api.meetup.com/Paris-js/events?desc=true&photo-host=public&page=1&sig_id=77326482&status=past&sig=253ccfbcfa69a2fccf31742ec420f87550bf8101`

**Comment by PierrickP** [comment]
https://app.evrybo.com/share/project/3797/30575/u74avioOMqurx8RvhOwa#38340

**Comment by Freddy03h** [comment]
Je m'en occupe !
