### ISSUE TITLE
Style Talk

### ISSUE THREAD

**Issue by PierrickP** [parisjs/parisjs-website#134]
Adapte `Talk` component with elements (picture and project / slide link)

**Comment by PierrickP** [comment]
https://app.evrybo.com/share/project/3797/30575/u74avioOMqurx8RvhOwa#38341

**Comment by PierrickP** [comment]
Author part: #142

**Comment by Freddy03h** [comment]
Mais si les slides c'est juste un lien on peut pas faire de preview, non ? Les slides peuvent être sur n'importe quel site, de n'importe quel format.

**Comment by PierrickP** [comment]
oui, n'importe quoi.
Ok on dit que c'est bon :ok_hand:
