### ISSUE TITLE
Fix translation

### ISSUE THREAD

**Issue by PierrickP** [parisjs/parisjs-website#137]
Some translation missing (on html attribut or form schema)

I don't know how to get the react-intl method for translate
See :
https://github.com/yahoo/react-intl/wiki/API#formatmessage
https://github.com/yahoo/react-intl/wiki/API#injectintl

**Comment by PierrickP** [comment]
Exemple: 
https://github.com/parisjs/parisjs-website/blob/e0d6594ab6d4cc4af41f5b4b99e8b0f9241feafb/components/TalkSubmissionContainer.js#L40
https://github.com/parisjs/parisjs-website/blob/e0d6594ab6d4cc4af41f5b4b99e8b0f9241feafb/components/TalkSubmissionContainer.js#L131

**Comment by fazouane-marouane** [comment]
Hello,

I was sober enough this morning to be able to write some code. So, this has been fixed on https://github.com/parisjs/parisjs-website/commit/471c5b7fee9a8a95cf7d68e85f75a9e295ffc704.
Tell me if I missed a non-translated text somewhere or if there's any mistranslation. 😊

**Comment by PierrickP** [comment]
😮  amazing !
