### ISSUE TITLE
Add missing sponsors in the website

### ISSUE THREAD

**Issue by DjebbZ** [parisjs/parisjs-website#150]
That's a lot of work...

**Comment by PierrickP** [comment]
Actually we too the decision to reset at january 2018 😄 
Cf de la reunion chez @molokoloco -> https://docs.google.com/document/d/1DBGDaJouJPcMRkoXPAm0G_Y_bkvP4FrQK3zTsvrQXq0/edit#heading=h.elzug75ex9af
