### ISSUE TITLE
Let's tweak the search

### ISSUE THREAD

**Issue by bobylito** [parisjs/parisjs-website#165]
Like any other tools a search engine is a tool that requires to be fine tuned. I only did a very quick config, so there might be some problems. Also the UI is probably lacking and could be improved. Let's make this issue the master one for all things that we find :)

 - [ ] search is by meetup, not by talks even though we search in talks (by @molokoloco https://imgur.com/a/7boVI query:`js`)

**Comment by molokoloco** [comment]
I have another proposition to make to you: "react-morph: A #React component for building #UI transitions between two states" https://github.com/brunnolou/react-morph 
So, when users clic the input, we can have a quick little animation from one state to another :-)
Do you think this is a good way to implement that with the current Agolia Framework you used ?
Thank you for the good work you have done @bobylito

**Comment by bobylito** [comment]
> So, when users clic the input, we can have a quick little animation from one state to another :-)

To be honest, ideally I'd stay on the same page. The PR was stalled and I didn't find a solution to stay on the same so we merged it but I would like to avoid the transition :)

> Thank you for the good work you have done @bobylito

Thanks for your kind words. This is only the beginning, with your help we will do better.
