### ISSUE TITLE
Github login doesn't work on Safari

### ISSUE THREAD

**Issue by mauricesvay** [parisjs/parisjs-website#190]
![Screenshot 2019-04-09 at 15 06 46](https://user-images.githubusercontent.com/265349/55802732-1e0bbe80-5ad9-11e9-959c-293eeae645b8.png)

At the end of the OAuth dance, the page just load inside the popup

**Comment by PierrickP** [comment]
Ca utilise le localstorage. J'ai appris que safari et local storage etait très capricieux
C'est peut-etre ca. Faut voir avec Hello.js, c'est le module qu'on utilise

**Comment by fazouane-marouane** [comment]
@mauricesvay T'arrives à reproduire l'erreur ?

**Comment by mauricesvay** [comment]
@fazouane-marouane je reproduis le problème, le but est toujours valide

**Comment by fazouane-marouane** [comment]
Okay pardon je viens de comprendre ! Le problème se produit bien après le login. Je regarde ce que je peux faire

**Comment by Freddy03h** [comment]
Merci @fazouane-marouane 😀
