### ISSUE TITLE
Rajouter des photos des meetups

### ISSUE THREAD

**Issue by sylvinus** [parisjs/parisjs-website#20]
Utile pour que les gens comprennent grosso modo l'ambiance des meetups, et ca rendrait le site plus vivant graphiquement ?

**Comment by revolunet** [comment]
vu qu'on est maintenant sur meetup, il y a des photos \o/ http://www.meetup.com/paris-js

close please

**Comment by DjebbZ** [comment]
Je suis plutôt pour des photos sur le site parisjs, vu qu'on a une page par meetup (même si on pointe pas dessus elle est générée par Jekyll). Rien n'empêche de poster sur meetup, mais ça serait cool de centraliser ça aussi sur le site. Après tous le site c'est le seul truc qui nous appartient à 100%, c'est notre vitrine, notre bébé... (je m'égare :D)

**Comment by molokoloco** [comment]
Quand j'y pense, sur Meetup, j'essaye d'illustrer avec au moins une photo
chaque event.... #souvenir
Un jour.. un beau slider responsive sur Parisjs.org ? :)

Le 26 mars 2015 10:02, Khalid Jebbari <notifications@github.com> a écrit :

> Je suis plutôt pour des photos sur le site parisjs, vu qu'on a une page
> par meetup (même si on pointe pas dessus elle est générée par Jekyll). Rien
> n'empêche de poster sur meetup, mais ça serait cool de centraliser ça aussi
> sur le site. Après tous le site c'est le seul truc qui nous appartient à
> 100%, c'est notre vitrine, notre bébé... (je m'égare :D)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parisjs/parisjs-website/issues/20#issuecomment-86413753>
> .
>



-- 
*Julien Guézennec *+336 61 75 64 98
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco <https://twitter.com/molokoloco/> -
http://b2bweb.fr
