### ISSUE TITLE
Passer de TravisCI à GitHub Actions

### ISSUE THREAD

**Issue by fazouane-marouane** [parisjs/parisjs-website#224]
Travis-ci prend beacoup trop de temps pour lancer le build. Si ça vous va, je peux migrer le déploiement vers github actions

<img width="600" alt="Screenshot 2021-01-11 at 19 57 21" src="https://user-images.githubusercontent.com/2125859/104225886-47dcdc80-5447-11eb-8e2f-196965d8c6aa.png">

**Comment by PierrickP** [comment]
Yes complemeent chaud ! 
Tu as besoin de mettre des secrets ? Je peux te passer sur l'orga si tu as besoin de faire des tests 
Moi quand je plug des trucs sur github action, j'ai toujours 5-10 runs de tests/fix xD

**Comment by fazouane-marouane** [comment]
Oui pareil ! Jamais j'ai réussi à le faire du premier coup xD
Sinon, je suis déjà sur l'orga mais je n'ai pas accès aux settings du projet. Je vais voir si je peux tout de même créer un workflow github action sans ça.
