### ISSUE TITLE
Phenomic est déprécié depuis quelques mois

### ISSUE THREAD

**Issue by fazouane-marouane** [parisjs/parisjs-website#228]
Le repo https://github.com/phenomic/phenomic est archivé depuis septembre et conseille de passer à nextjs.
Ça vous va si je regarde ça ?

**Comment by fazouane-marouane** [comment]
Pour info, j'ai migré le projet vers nextjs, mis à jour les autres dépendances et apporté quelques améliorations (dont l'histoire des avatars). Vous pouvez voir le résultat ici https://test-parisjs-website.vercel.app/
J'ai mis une app OAuth de test dessus pour vérifier que tout marchait. Je pense proposer deux PRs dans les prochains jours (une pour nextjs et l'autre pour les avatars).

Seule contrainte c'est qu'on doit utiliser Vercel(zeit) ou un service équivalent étant donné que nextjs ne permet pas d'exporter  en html standalone quand on utilise le module d'i18n.
Le bon côté c'est qu'on gagne vachement en perf ! N'hésitez pas me dire ce que vous en penser 😉

**Comment by PierrickP** [comment]
Je dis oui ! Tu es une machine

J'ai vu 2-3 changements de css. Je sais pas si c'est volontaires. Je laisse @mauricesvay approuver cette partie, c'est lui le chef du design.

Ok pour vercel, j'ai rien contre.

**Comment by mauricesvay** [comment]
Ça me parait top 👍 
Un peu dommage que les fonctions d'internationalisation ne sont pas compatibles avec l'export statique 😞

**Comment by fazouane-marouane** [comment]
Super ! Du coup je pousse la première PR dans quelques minutes.

@mauricesvay Oui c'est ultra dommage en effet. Mais le bon côté, c'est la partie optimisation automatique d'images qu'on aura au passage à Vercel 😄
