### ISSUE TITLE
The link to the Meetup page is dead

### ISSUE THREAD

**Issue by DjebbZ** [parisjs/parisjs-website#259]
The thing is, searching for "Paris.js" or "ParisJS" displays the meetup...

![Screenshot 2023-07-05 at 17 20 36](https://github.com/parisjs/parisjs-website/assets/77278/569b72da-3da7-453d-b534-b890be7ba251)

...but clicking the link leads to a big "404" page.

![Screenshot 2023-07-05 at 17 20 48](https://github.com/parisjs/parisjs-website/assets/77278/9676fdc8-e1d3-45a8-9490-ff33529fe990)

Something's wrong?

**Comment by PierrickP** [comment]
Je ne sais pas qui a fait le changement, l'URL correct est https://www.meetup.com/fr-FR/paris-js/ avec "p" de Paris en minuscule

**Comment by PierrickP** [comment]
C'est con car l'url fonctionne pas 
![image](https://github.com/parisjs/parisjs-website/assets/1214544/1ba132bb-e5f7-45bd-9b1d-b63727fc63ed)

**Comment by bloodyowl** [comment]
Closed by 7b6fe6a
