### ISSUE TITLE
Version francophone du site

### ISSUE THREAD

**Issue by MathRobin** [parisjs/parisjs-website#53]
On est ParisJS, donc une association française, mais notre site est exclusivement anglophone. Même si je suis d'accord qu'un dev qui ne parle pas un minimum anglais, il est dans la merde jusqu'au cou.
J'ai pu constater que de nombreuses personnes, en l’occurrence des collègues pour la majorité ont abandonné l'idée de venir parce que peur de "pas comprendre parce qu'il risque d'y avoir de l'anglais".
Le dernier talk en anglais auquel j'ai assisté était celui en octobre 2011 (gozala et ses streamers), ça remonte.

A mon avis, une version francophone ne serait pas inutile, tout en préservant bien sur la version anglophone.

Encore une fois, je veux bien mettre la main à la pâte.

**Comment by francois2metz** [comment]
Avec jekyll on devrait maintenant avoir un /fr/ et un /en/ propre qui n'embéteront pas le référencement.

**Comment by PierrickP** [comment]
-> https://github.com/parisjs/parisjs-website/issues/124
