### ISSUE TITLE
Enlever les emails sur /program.html

### ISSUE THREAD

**Issue by PierrickP** [parisjs/parisjs-website#69]
Suite a une demande sur la ML, il faudrait **ne pas afficher** les adresses emails des speakers.

**Comment by revolunet** [comment]
toujours d'actu ou on peut close ?

**Comment by MathRobin** [comment]
Je sais pas pour vous, mais finalement, j'ai jamais été spammé ce qui était ma principale crainte. Rarement une bonne idée d'exposer les mails en public. Mais bon, a priori, chez gmail, l'anti-spam a été efficace.
C'est bon pour moi, on peut clore.

**Comment by DjebbZ** [comment]
Closons alors, closons :)
