### ISSUE TITLE
Vidéos

### ISSUE THREAD

**Issue by revolunet** [parisjs/parisjs-website#81]
Ajouter les vidéos existantes

http://www.dailymotion.com/ParisJS

**Comment by DjebbZ** [comment]
Oh ! Qui les a uploadé ?

**Comment by mauricesvay** [comment]
Je crois que c'était moi :)

**Comment by revolunet** [comment]
yep that's awesome. comment s'appelle notre cameraman qui filme toujours avec son smartphone ?

**Comment by DjebbZ** [comment]
Tariq (ou Tareq).

**Comment by revolunet** [comment]
un email ?

**Comment by DjebbZ** [comment]
Je te l'envoie par mail dès que je l'ai.

Khalid aka DjebbZ
@Dj3bbZ

**Comment by molokoloco** [comment]
Tariq(?) m'avais déjà donné les vidéos pour 16 ParisJS (découpées en une
40e de fichiers ~40Go))
Il me faudrait le *login Dailymotion* please
Je vais les uploader, la qualité vidéo/son n'est pas top mais ca fait
toujours des traces et les dates ;)

JG



2015-03-19 10:55 GMT+01:00 Khalid Jebbari <notifications@github.com>:

> Je te l'envoie par mail dès que je l'ai.
>
> Khalid aka DjebbZ
> @Dj3bbZ
>
> On Thu, Mar 19, 2015 at 10:19 AM, Julien Bouquillon <
> notifications@github.com> wrote:
>
> > un email ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/parisjs/parisjs-website/issues/81#issuecomment-83435657
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parisjs/parisjs-website/issues/81#issuecomment-83459781>
> .
>



-- 
*Julien Guézennec *+336 61 75 64 98
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco <https://twitter.com/molokoloco/> -
http://b2bweb.fr

**Comment by revolunet** [comment]
awesome!

**Comment by molokoloco** [comment]
Je ne sais pas si Khalid t'a donné son mail mais voilà au moins le profil
meetup de Tarik :

http://www.meetup.com/Paris-js/members/28940422/

On Fri, Mar 20, 2015 at 10:26 AM, Julien G <molokoloco@gmail.com> wrote:

>
> Tariq(?) m'avais déjà donné les vidéos pour 16 ParisJS (découpées en une
> 40e de fichiers ~40Go))
> Il me faudrait le *login Dailymotion* please
> Je vais les uploader, la qualité vidéo/son n'est pas top mais ca fait
> toujours des traces et les dates ;)
>
> JG
>
>
>
> 2015-03-19 10:55 GMT+01:00 Khalid Jebbari <notifications@github.com>:
>
>> Je te l'envoie par mail dès que je l'ai.
>>
>> Khalid aka DjebbZ
>> @Dj3bbZ
>>
>> On Thu, Mar 19, 2015 at 10:19 AM, Julien Bouquillon <
>> notifications@github.com> wrote:
>>
>> > un email ?
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/parisjs/parisjs-website/issues/81#issuecomment-83435657
>> >
>>
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/parisjs/parisjs-website/issues/81#issuecomment-83459781>
>> .
>>
>
>
>
> --
> *Julien Guézennec *+336 61 75 64 98
> 13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
> molokoloco@gmail.com - @molokoloco <https://twitter.com/molokoloco/> -
> http://b2bweb.fr
>
> --
> You received this message because you are subscribed to the Google Groups
> "ParisJS" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to parisjs+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.
>



-- 
Adrien Risser,
Freelance Node.js Consultant
M. +33 6 59 60 32 58

**Comment by molokoloco** [comment]
Et hop ! Uploadé une mine d'infos...
5 pages de vidéos Paris JS sur Dailymotion !!! (En gros *du ParisJS 21 au
ParisJS 40*... YEAH!)
Un grand merci à Tarik pour les vidéos, un grand merci à moi pour l'upload
et le nommage ;)

http://www.dailymotion.com/user/ParisJS/ Yo :)

J'essaye de ranger par playlist mais c’est difficile avec Dailymotion.. ca
bug un max, probablement du cache, et les infos ne sont pas consistantes
#badBoys
Nb : Heureusement que leur uploader sur le site marche mieux que leur "mass
uploader" en adobe air ^^
https://twitter.com/molokoloco/status/580389050923782144


Julien G



2015-03-24 13:27 GMT+01:00 Adrien Risser <risseraka@gmail.com>:

> Je ne sais pas si Khalid t'a donné son mail mais voilà au moins le profil
> meetup de Tarik :
>
> http://www.meetup.com/Paris-js/members/28940422/
>
> On Fri, Mar 20, 2015 at 10:26 AM, Julien G <molokoloco@gmail.com> wrote:
>
>>
>> Tariq(?) m'avais déjà donné les vidéos pour 16 ParisJS (découpées en une
>> 40e de fichiers ~40Go))
>> Il me faudrait le *login Dailymotion* please
>> Je vais les uploader, la qualité vidéo/son n'est pas top mais ca fait
>> toujours des traces et les dates ;)
>>
>> JG
>>
>>
>>
>> 2015-03-19 10:55 GMT+01:00 Khalid Jebbari <notifications@github.com>:
>>
>>> Je te l'envoie par mail dès que je l'ai.
>>>
>>> Khalid aka DjebbZ
>>> @Dj3bbZ
>>>
>>> On Thu, Mar 19, 2015 at 10:19 AM, Julien Bouquillon <
>>> notifications@github.com> wrote:
>>>
>>> > un email ?
>>> >
>>> > —
>>> > Reply to this email directly or view it on GitHub
>>> > <
>>> https://github.com/parisjs/parisjs-website/issues/81#issuecomment-83435657
>>> >
>>>
>>> > .
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/parisjs/parisjs-website/issues/81#issuecomment-83459781>
>>> .
>>>
>>
>>
>>
>> --
>> *Julien Guézennec *+336 61 75 64 98
>> 13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
>> molokoloco@gmail.com - @molokoloco <https://twitter.com/molokoloco/> -
>> http://b2bweb.fr
>>
>> --
>> You received this message because you are subscribed to the Google Groups
>> "ParisJS" group.
>> To unsubscribe from this group and stop receiving emails from it, send an
>> email to parisjs+unsubscribe@googlegroups.com.
>> For more options, visit https://groups.google.com/d/optout.
>>
>
>
>
> --
> Adrien Risser,
> Freelance Node.js Consultant
> M. +33 6 59 60 32 58
>
> --
> You received this message because you are subscribed to the Google Groups
> "ParisJS" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to parisjs+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.
>



-- 
*Julien Guézennec *+336 61 75 64 98
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco <https://twitter.com/molokoloco/> -
http://b2bweb.fr

**Comment by revolunet** [comment]
Cool, merci Ju c top :)
Bon et sinon on a toujours pas le compte twitter de ce fameux Tariq pour le remercier ?
Reste donc plus qu'a ajouter une info "meta" dans le post.md pour lier à la video ?

**Comment by mauricesvay** [comment]
Bravo :+1:

**Comment by molokoloco** [comment]
@twirrek
Tarik@bensakhria.com

Ok

**Comment by revolunet** [comment]
ok c ajouté dans les metas !

**Comment by molokoloco** [comment]
Énorme ! https://github.com/parisjs/parisjs-website/pull/83

Merci m'sieur, la belle équipe :D
Je regarde les vidéos pour le #33 demain sur mon pc, il y avait
effectivement un event sur lequel je ne trouvais pas d'infos sur notre site
et donc je n'arrivais pas à les nommer.. bref

"We make meta data porn" comme on dit ;)
Le 26 mars 2015 00:16, "Julien Bouquillon" <notifications@github.com> a
écrit :

**Comment by DjebbZ** [comment]
Énorme les gars. Énorme.

**Comment by DjebbZ** [comment]
Haha, il doit y avoir un code par défaut dans le template, mais il y a pas de liens (gros ceux qu'on vient d'ajouter) qui pointent vers la même vidéo Youtube : http://www.youtube.com/watch?v=oHg5SJYRHA0. Par exemple sur le meetup 40 lightning sur Hello.js.

**Comment by DjebbZ** [comment]
J'ai compris : @revolunet dans ta PR t'utilises pas "post.videos" quand ya une seule vidéo.

**Comment by molokoloco** [comment]
Mec... tu gères :-D

**Comment by molokoloco** [comment]
+1 Merci!!!! A vous à vous deux! :)

**Comment by molokoloco** [comment]
Yeah, super boulot !
Z'assurez les gens.

**Comment by DjebbZ** [comment]
J'ai corrigé le problème des vidéos sur le site, tous les talks avec une seule vidéo pointant vers une vidéo pourrie sur le site. J'ai utilisé prose.io pour le faire (vous savez, l'interface web pour Github+Jekyll). Maintenant tous les liens sont bons, je fais faire une méga-annonce sur la ML.

On peut close ?

**Comment by revolunet** [comment]
Oops, bien vu!
