### ISSUE TITLE
Ajouter un lien vers parisjstalks.nodejitsu.com/sponsoring

### ISSUE THREAD

**Issue by risseraka** [parisjs/parisjs-website#91]
Le formulaire pour le sponsoring a été ajouté à https://github.com/parisjs/parisjs-talks-submit et déployé par @francois2metz sur http://parisjstalks.nodejitsu.com/sponsoring.

Cette issue est là pour se souvenir qu'il faut changer la partie "host next Paris.js" sur http://parisjs.org/ en ajoutant un lien vers une page à la http://parisjs.org/program.html et possiblement changer le wiki https://github.com/parisjs/parisjs-website/wiki/Be-a-ParisJS-Host pour expliquer que la demande se fait sur le site de préférence.

**Comment by DjebbZ** [comment]
Le lien vers le formulaire est dans le wiki (depuis un bout de temps), le lien vers le wiki sur le site. Site -> Wiki -> formulaire. On est bon !
